### ISSUE TITLE
Make it noarch again?

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/mne-qt-browser-feedstock#19]
### Comment:

Currently, this package is not-noarch because we have a platform-dependent dependency, namely `pyopengl` on macOS.

I'm wondering if installing this (small) package on **all** platforms would be such a bad idea, even if it's only used on macOS?

This would allow us to make `mne-qt-browser` `noarch` again, meaning we'd have a single package that runs on all supported platforms and Python versions automatically… WDYT?

**Comment by larsoner** [comment]
If it's always installable on all platforms and `mne-qt-browser` doesn't try to use it unless asked (except for macOS where we try to force it to avoid some segfaults IIRC) then it's okay with me
