### ISSUE TITLE
Entry point is broken

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/mne-qt-browser-feedstock#5]
```
❯ mne-qt-browser
Traceback (most recent call last):
  File "/Users/hoechenberger/miniforge3/envs/mne-qt-browser/bin/mne-qt-browser", line 6, in <module>
    from mne_qt_browser.__main__ import main
ModuleNotFoundError: No module named 'mne_qt_browser.__main__'
```
Not sure if this has been fixed in `mne-qt-browser:main` already?

We're definitely missing an entry point test here.

**Edit**
There's no entry point upstream anymore. Was this removed intentionally?
@larsoner @marsipu

**Comment by marsipu** [comment]
Yes, I think we removed the entry point intentionally and forgot to remove it here, thanks.
